apiVersion: v1
kind: Service
metadata:
  labels:
    app: net5app
  namespace: op1ns
  name: net5app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 5001
  selector:
    app: net5app